version: 2.1

orbs:
  cfa: continuousauth/npm@1.0.2
  node: electronjs/node@1.2.0

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          executor: node/macos
          name: test-mac-<< matrix.node-version >>
          test-steps:
            - run: yarn build
            - run: yarn test
          use-test-steps: true
          matrix:
            alias: test
            parameters:
              node-version:
                - 20.5.0
                - 18.17.0
                - 16.20.1
                - 14.21.3
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
