steps-test: &steps-test
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
          - v1-dependencies-{{ arch }}
    - run: yarn --frozen-lockfile
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
    - run: yarn build
    - run: yarn test

version: 2.1

orbs:
  cfa: continuousauth/npm@1.0.2

jobs:
  test:
    macos:
      xcode: "13.4.1"
    resource_class: macos.x86.medium.gen2
    <<: *steps-test

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release

