version: 2.1

orbs:
  cfa: continuousauth/npm@2.1.0
  node: electronjs/node@2.3.0

workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test:
          executor: node/macos
          name: test-mac-<< matrix.node-version >>
          override-ci-command: yarn install --frozen-lockfile --ignore-engines
          test-steps:
            - node/install-rosetta
            - run: yarn build
            - run: yarn lint
            - run: yarn test
          use-test-steps: true
          matrix:
            alias: test
            parameters:
              node-version:
                - 20.5.0
                - 18.17.0
                - 16.20.1
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
